apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-{{ .Release.Name }}
subsets:
  - addresses:
    - ip: {{ .Values.ipAddress }}
    ports:
    - port: {{ .Values.port.target }}
      name: {{ .Values.port.name }}