---
apiVersion: v2
appVersion: 5.4.6
description: A fork of Sonarr to work with movies à la Couchpotato
name: radarr
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - radarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/radarr
icon: https://github.com/Radarr/Radarr/blob/aphrodite/Logo/512.png?raw=true
sources:
  - https://github.com/Radarr/Radarr
  - https://github.com/k8s-at-home/container-images
dependencies:
  - name: common
    version: 3.1.0
    repository: https://bjw-s.github.io/helm-charts/