---
apiVersion: v2
appVersion: 21.1.20221201
description: NZBGet is a Usenet downloader client
name: nzbget
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - nzbget
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/nzbget
icon: https://avatars1.githubusercontent.com/u/3368377?s=400&v=4
sources:
  - https://nzbget.net/
  - https://github.com/k8s-at-home/container-images
dependencies:
- name: common
  version: 1.2.1
  repository: https://bjw-s.github.io/helm-charts/