{{ if .Values.global.config.auto }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: configarr-config
data:
  config.yaml: |
    {{- include "config.configarr" . | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: configarr-init-
  annotations:
    argocd.argoproj.io/hook: PostSync
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 15
  template:
    spec:
      containers:
        - name: configarr
          image: ghcr.io/graytonio/configarr:0.0.2
          command: ["/configarr", "--config=/config/config.yaml", "--verbose"]
          volumeMounts:
            - name: config-file
              mountPath: /config
      restartPolicy: Never
      volumes:
        - name: config-file
          configMap:
              name: configarr-config
              items:
                - key: config.yaml
                  path: config.yaml
{{end}}