apiVersion: v1
kind: ConfigMap
metadata:
    name: configarr-config
    namespace: {{ .Release.Namespace }}
data:
    config.yaml: |
        services:
        {{- if .Values.radarr.enabled }}
          - name: radarr
            address: {{ .Release.Name }}-radarr.{{ .Release.Namespace }}.svc
            port: {{ .Values.radarr.service.main.ports.http.port }}
            config:
            {{- if .Values.radarr.persistence.media.enabled }}
              rootfolder:
                - name: Movies
                  path: {{ .Values.radarr.persistence.media.mountPath }}
            {{- end }}
              downloadclient:
              {{- if .Values.transmission.enabled }}
                - name: Transmission
                  appType: Transmission
                  fields:
                    - name: host
                      value: {{ .Release.Name }}-transmission.{{ .Release.Namespace }}.svc
                    - name: port
                      value: {{ .Values.transmission.service.main.ports.http.port }}
              {{- end }}
              {{- if .Values.nzbget.enabled }}
                - name: NZBget
                  appType: NZBget
                  fields:
                    - name: host
                      value: {{ .Release.Name }}-nzbget.{{ .Release.Namespace }}.svc
                    - name: port
                      value: {{ .Values.nzbget.service.main.ports.http.port }}
                    - name: tvCategory
                      value: "Movies"
                    - name: username
                      value: {{ .Values.nzbget.env.NZBGET_USER | default "nzbget" | quote }}
                    - name: password
                      value: {{ .Values.nzbget.env.NZBGET_PASS | default "tegbzn6789" | quote }}
              {{- end }}
        {{- end }}
        {{- if .Values.sonarr.enabled }}
          - name: sonarr
            address: {{ .Release.Name }}-sonarr.{{ .Release.Namespace }}.svc
            port: {{ .Values.sonarr.service.main.ports.http.port }}
            config:
            {{- if .Values.sonarr.persistence.media.enabled }}
              rootfolder:
                - name: Movies
                  path: {{ .Values.sonarr.persistence.media.mountPath }}
            {{- end }}
              downloadclient:
              {{- if .Values.transmission.enabled }}
                - name: Transmission
                  appType: Transmission
                  fields:
                    - name: host
                      value: {{ .Release.Name }}-transmission.{{ .Release.Namespace }}.svc
                    - name: port
                      value: {{ .Values.transmission.service.main.ports.http.port }}
              {{- end }}
              {{- if .Values.nzbget.enabled }}
                - name: NZBget
                  appType: NZBget
                  fields:
                    - name: host
                      value: {{ .Release.Name }}-nzbget.{{ .Release.Namespace }}.svc
                    - name: port
                      value: {{ .Values.nzbget.service.main.ports.http.port }}
                    - name: tvCategory
                      value: "Series"
                    - name: username
                      value: {{ .Values.nzbget.env.NZBGET_USER | default "nzbget" | quote }}
                    - name: password
                      value: {{ .Values.nzbget.env.NZBGET_PASS | default "tegbzn6789" | quote }}
              {{- end }}
        {{- end }}
        {{- if or .Values.sonarr.enabled .Values.radarr.enabled }}
          - name: prowlarr
            address: {{ .Release.Name }}-prowlarr.{{ .Release.Namespace }}.svc
            port: {{ .Values.prowlarr.service.main.ports.http.port }}
            config:
              applications:
              {{- if .Values.sonarr.enabled }}
                - name: sonarr
                  appType: Sonarr
              {{- end }}
              {{- if .Values.radarr.enabled }}
                - name: radarr
                  appType: Radarr
              {{- end }}
        {{ end }}
