---
apiVersion: v2
appVersion: 0.4.9-develop
description: Indexer manager/proxy built on the popular arr net base stack to integrate with your various PVR apps.
name: prowlarr
version: 4.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - prowlarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/prowlarr
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png
sources:
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/k8s-at-home/container-images
dependencies:
- name: common
  version: 1.1.3
  repository: https://bjw-s.github.io/helm-charts/